---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deploy.name}}
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: {{.Values.deploy.containername}}
        image: cabanitos/mynginx:1.1
        ports:
        - containerPort: {{.Values.deploy.port}}
