---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name_deploy}}
spec:
  selector:
    matchLabels:
      app: {{.Values.deployment.labels}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.labels}}
    spec:
      containers:
      - name: {{.Values.deployment.container_name}}
        image: cabanitos/jenkins-server-k8s-docker:1.0.3
        env:
          - name: DOCKER_HOST
            value: "tcp://localhost:2375"
        ports:
          - containerPort: 8080

      
      - name: {{.Values.deployment.container_name_dind}}
        image: docker:dind
        securityContext:
          privileged: true
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        ports:
          - containerPort: 2375
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name_svc}}
spec:
  selector:
    app: {{.Values.deployment.labels}}
  type: NodePort
  ports:
  - port: 8080
    targetPort: {{.Values.service.target_port}}
    nodePort: {{.Values.service.nodeport}}

      
